import { describe, expect, it, vi } from "vitest";
vi.mock("server-only",()=>({}));
import type { PostgresRpcClient } from "../../lib/project-intelligence/adapters/postgres";
import { projectCeoCommandSchema, type ProjectCeoCommand } from "../../lib/project-intelligence/delivery/projectceo/command-contract";
import { ProjectCeoCommandService } from "../../lib/project-intelligence/delivery/projectceo/command-service";
const id="abcdef00-0000-4000-8000-000000000001";
const geometry={pdfPageIndex:0,pdfCrop:{left:0,top:0,right:1,bottom:1},rotationDegrees:90 as const,units:"mm" as const,pageToPreviewTransform:[1,0,0,1,0,0] as [number,number,number,number,number,number]};
const command:Extract<ProjectCeoCommand,{kind:"bind_pdf_dwg_sheet_sidecar"}>={contractVersion:"projectceo-command/0.1",projectId:id,commandId:id,kind:"bind_pdf_dwg_sheet_sidecar",payload:{packageId:id,confirmationId:id,sheetId:"Sheet-A",sheetRevisionId:"Rev-A",reason:"Declared geometry",geometry}};
function fixture(patch:Record<string,unknown>={},enabled="true",packageId=id,replay=false,options:{projectScope?:boolean;operation?:string;extraRoot?:boolean;error?:boolean}={}){
 const calls:{name:string;args:Readonly<Record<string,unknown>>}[]=[];
 const result={...geometry,sidecarId:id,schemaVersion:"r1-pdf-sheet-sidecar/1",confirmationId:id,sheetId:"Sheet-A",sheetRevisionId:"Rev-A",pdfAssetVersionId:id,pdfSha256:"a".repeat(64),geometryEvidence:"architect_declared",pageMetadataVerification:"not_verified",createdAt:"2026-09-16T00:00:00.000000Z",conversionStatus:"unconfirmed",warning:"PDF предоставлен архитектором; DWG conversion не подтверждён",...patch};
 const client:PostgresRpcClient={schema:(schema)=>({rpc:async(fn,args={})=>{calls.push({name:`${schema}.${fn}`,args});if(fn==="list_projects")return {data:{contractVersion:"project-ceo-foundation/0.1",requestId:"scope",error:null,data:[{projectId:id,organizationId:id,role:"architect",stateRevision:42,accessScope:options.projectScope?"project":"package",packageId}]},error:null};if(fn!==command.kind||schema!=="projectceo_api")throw Error("unexpected RPC");if(options.error)return {data:null,error:{code:"P1103",message:"private detail"}};return {data:{operation:options.operation??command.kind,replay,result,...(options.extraRoot?{privateInfo:"not allowed"}:{})},error:null};}})};
 return {calls,result,service:new ProjectCeoCommandService({client,documentationEnabled:enabled})};
}
describe("sidecar request door",()=>{
 it("accepts declared-only DTO",()=>{expect(projectCeoCommandSchema.safeParse(command).success).toBe(true);for(const k of ["actorId","pdfSha256","sidecarId","geometryEvidence"]){expect(projectCeoCommandSchema.safeParse({...command,payload:{...command.payload,[k]:"forged"}}).success).toBe(false);}expect(projectCeoCommandSchema.safeParse({...command,payload:{...command.payload,geometry:{...geometry,pageToPreviewTransform:[1,2,2,4,0,0]}}}).success).toBe(false);});
 it.each([false,true])("normalizes UUIDs, preserves sheet case and exact geometry replay=%s",async(replay)=>{const f=fixture({pdfCrop:{bottom:1,right:1,top:0,left:0}},"true",id,replay);const r=await f.service.execute({...command,projectId:id.toUpperCase(),commandId:id.toUpperCase(),payload:{...command.payload,packageId:id.toUpperCase(),confirmationId:id.toUpperCase()}},"http");expect(r).toMatchObject({status:"completed",stateRevision:42,replay,result:f.result});expect(f.calls[1]?.args).toEqual({project_id:id,package_id:id,confirmation_id:id,sheet_id:"Sheet-A",sheet_revision_id:"Rev-A",pdf_page_index:0,pdf_crop:geometry.pdfCrop,rotation_degrees:90,units:"mm",page_to_preview_transform:geometry.pageToPreviewTransform,reason:command.payload.reason,idempotency_key:`ui:${id}:${command.kind}:${id}`});});
 it("allows project scope",async()=>{const f=fixture({},"true",id,false,{projectScope:true});expect(await f.service.execute(command,"http")).toMatchObject({status:"completed"});});
 it.each([{operation:"wrong"},{extraRoot:true}])("rejects envelope mismatch %j",async(options)=>{const f=fixture({},"true",id,false,options);expect(await f.service.execute(command,"http")).toMatchObject({status:"error"});});
 it("maps database errors safely",async()=>{const f=fixture({},"true",id,false,{error:true});const r=await f.service.execute(command,"http");expect(r).toMatchObject({status:"error"});expect(JSON.stringify(r)).not.toContain("private detail");});
 it("rejects extra nested geometry keys",()=>{expect(projectCeoCommandSchema.safeParse({...command,payload:{...command.payload,geometry:{...geometry,authority:"forged"}}}).success).toBe(false);});
 it("module off has no RPC",async()=>{const f=fixture({},"false");expect(await f.service.execute(command,"http")).toMatchObject({status:"unavailable"});expect(f.calls).toHaveLength(0);});
 it("wrong package has no mutation",async()=>{const f=fixture({},"true","abcdef00-0000-4000-8000-000000000002");expect(await f.service.execute(command,"http")).toMatchObject({status:"error"});expect(f.calls).toHaveLength(1);});
 it.each([{confirmationId:"abcdef00-0000-4000-8000-000000000009"},{sheetRevisionId:"Rev-B"},{geometryEvidence:"verified"},{pageMetadataVerification:"verified"},{conversionStatus:"confirmed"},{reason:"private"},{sheetId:"sheet-a"},{pdfPageIndex:1},{pdfCrop:{left:0,top:0,right:0.5,bottom:1}},{pageToPreviewTransform:[1,2,2,4,0,0]}])("rejects changed/unsafe result %j",async(patch)=>{const f=fixture(patch);expect(await f.service.execute(command,"http")).toMatchObject({status:"error"});});
});
